# Generated by Django 5.1.1 on 2024-11-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_is_certifiqued'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='documentoId',
            field=models.CharField(default='000', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tipoDocument',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
